### ISSUE TITLE
CSS MISSING??

### ISSUE THREAD

**Issue by Kasper-Liu** [spcccomputerclub/spcccomputerclub.github.io#3]
Things to change:
add .DS_STORE in gitignore it's really annoying for non mac users
and is the CSS

**Comment by Kasper-Liu** [comment]
I'm not a computer club commitee member btw

**Comment by spcccomputerclub** [comment]
Oh hi Kasper! Its not css missing lol; its just that Im trying to add my dependencies as git submodules to my project (new technology to me) and now it becomes quite problematics

**Comment by spcccomputerclub** [comment]
@Kasper-Liu Now solving the problem, be patient lol

**Comment by Kasper-Liu** [comment]
ahh icic so the entire theme (blowfish) is missing

**Comment by Kasper-Liu** [comment]
I guess try and revert back to commit 0e272c first on the major branch
 https://github.com/spcccomputerclub/spcccomputerclub.github.io/commit/0e272c5b063bc5c0c26345e5c695feee4c487765
 
then start a new branch for testing the submodule

**Comment by spcccomputerclub** [comment]
I have tried to revert the commit but it seems to fail, im now trying git submodule update --remote --merge

**Comment by Kasper-Liu** [comment]
ok I'll fork this and prob try and fix it

**Comment by Kasper-Liu** [comment]
btw please contact me via discord: ||𝓚𝓪𝓼𝓹𝓮𝓻||#8043
or my tel number 6596 2300 cause this is a bit indirect thanks

**Comment by Kasper-Liu** [comment]
whatsapp preferred

**Comment by spcccomputerclub** [comment]
Lol thx if you can fix it you can open a PR I guess

**Comment by spcccomputerclub** [comment]
@Kasper-Liu  Problem solved, check the website: https://spcccomputerclub.github.io/

**Comment by Kasper-Liu** [comment]
nice nice
